#pragma once

#include <functional>
#include <ostream>

#include <boost/filesystem/path.hpp>

#include "libslic3r/BoundingBox.hpp"
#include "libslic3r/ExPolygon.hpp"

namespace Slic3r {

// Compute the projector bounding box in bed-coordinate mm.
// When display_width_mm/display_height_mm are both > 0 they are used directly.
// Otherwise falls back to a square whose side equals max(bed width, bed height),
// centred on the bed.
BoundingBoxf sla_proj_bbox(
    const BoundingBoxf &bed_bbox,
    double              display_width_mm,
    double              display_height_mm);

// Render a solid-white (fully-exposed) PGM P5 frame into os.
void render_sla_synth_pgm_frame(std::ostream &os, int width, int height);

// Render a rasterised slice of expolygons as a PGM P5 frame into os.
// expolys must be given in libslic3r internal (scaled) coordinates;
// proj_bbox is in mm and defines the projector illumination area.
void render_sla_slice_pgm_frame(
    std::ostream       &os,
    int                 width,
    int                 height,
    const ExPolygons   &expolys,
    const BoundingBoxf &proj_bbox);

// Pipe frame_count PGM frames (generated by render_frame(os, frame_idx))
// directly into ffmpeg and encode them as an H.265 MKV at output_path.
// Throws Slic3r::ExportError on any failure.
void encode_sla_video_with_ffmpeg_or_throw(
    const boost::filesystem::path                     &output_path,
    int                                                fps,
    bool                                               lossless,
    size_t                                             frame_count,
    const std::function<void(std::ostream &, size_t)> &render_frame);

} // namespace Slic3r
