#!/usr/bin/env python3
"""Generate a setup-specific override INI for high-channel logical extruder printers.

This keeps the printer profile stable (for example 100 logical channels) while allowing
one override INI per physical setup.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List


def parse_channel_csv(raw: str | None, channels: int) -> List[int]:
    if raw is None or raw.strip() == "":
        return []
    out: List[int] = []
    for token in raw.split(","):
        token = token.strip()
        if token == "":
            continue
        idx = int(token)
        if idx < 1 or idx > channels:
            raise ValueError(f"Channel index out of range: {idx} (valid 1..{channels})")
        out.append(idx)
    return sorted(set(out))


def parse_nozzle_map(raw: str | None, channels: int, default_nozzle: float) -> List[float]:
    nozzles = [default_nozzle] * channels
    if raw is None or raw.strip() == "":
        return nozzles

    for token in raw.split(","):
        token = token.strip()
        if token == "":
            continue
        if "=" not in token:
            raise ValueError(f"Invalid nozzle map token '{token}', expected CH=DIAMETER")
        ch_str, d_str = token.split("=", 1)
        ch = int(ch_str.strip())
        if ch < 1 or ch > channels:
            raise ValueError(f"Nozzle map channel out of range: {ch} (valid 1..{channels})")
        diameter = float(d_str.strip())
        if diameter <= 0.0:
            raise ValueError(f"Nozzle diameter must be > 0 for channel {ch}")
        nozzles[ch - 1] = diameter

    return nozzles


def build_default_colors(channels: int) -> List[str]:
    palette = [
        "#FFB347", "#A0A0A0", "#5BC0EB", "#FDE74C",
        "#9BC53D", "#E55934", "#FA7921", "#6A4C93",
    ]
    return [palette[i % len(palette)] for i in range(channels)]


def format_float_list(values: List[float]) -> str:
    return ",".join(f"{v:g}" for v in values)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a setup-specific channel override INI")
    parser.add_argument("--output", type=Path, required=True, help="Output INI path")
    parser.add_argument("--channels", type=int, default=100, help="Number of logical channels")
    parser.add_argument("--default-nozzle", type=float, default=0.4, help="Default nozzle diameter for all channels")
    parser.add_argument(
        "--nozzle-map",
        default="",
        help="Comma list of per-channel overrides, format: CH=DIAMETER,CH=DIAMETER",
    )
    parser.add_argument(
        "--sla-channels",
        default="",
        help="Comma list of 1-based channel indices marked as SLA-capable",
    )
    parser.add_argument(
        "--sla-video-name",
        default="resin_basic",
        help="Video name assigned to SLA channels",
    )
    parser.add_argument(
        "--embed-sla-video",
        action="store_true",
        help="Set SLA video embed flags to 1 for SLA channels",
    )
    parser.add_argument(
        "--synthesize-sla-video",
        action="store_true",
        help="Set SLA video synthesis flags to 1 for SLA channels",
    )
    parser.add_argument(
        "--toolchange-macro",
        default="BIOSLICER_ROUTE_TOOLCHANGE CHANNEL=[next_extruder]",
        help="Toolchange gcode macro line used to route logical channels",
    )
    args = parser.parse_args()

    channels = args.channels
    if channels < 1 or channels > 255:
        raise ValueError("--channels must be in range 1..255")

    nozzles = parse_nozzle_map(args.nozzle_map, channels, args.default_nozzle)
    sla_channels = parse_channel_csv(args.sla_channels, channels)

    filament_diameter = [1.75] * channels
    extruder_offset = ["0x0"] * channels
    colors = build_default_colors(channels)

    sla_flags = [0] * channels
    synth_flags = [0] * channels
    embed_flags = [0] * channels
    video_names = [""] * channels
    video_paths = [""] * channels

    for ch in sla_channels:
        idx = ch - 1
        sla_flags[idx] = 1
        if args.synthesize_sla_video:
            synth_flags[idx] = 1
        if args.embed_sla_video:
            embed_flags[idx] = 1
        video_names[idx] = args.sla_video_name

    lines = [
        "; Auto-generated by gen_channel_setup_override.py",
        f"nozzle_diameter = {format_float_list(nozzles)}",
        f"filament_diameter = {format_float_list(filament_diameter)}",
        f"extruder_offset = {','.join(extruder_offset)}",
        f"extruder_colour = {';'.join(colors)}",
        f"sla_material_extruder = {','.join(str(v) for v in sla_flags)}",
        f"sla_material_video_synthesize = {','.join(str(v) for v in synth_flags)}",
        f"sla_material_video_names = {';'.join(video_names)}",
        f"sla_material_video_paths = {';'.join(video_paths)}",
        f"sla_material_video_embed = {','.join(str(v) for v in embed_flags)}",
        "toolchange_gcode = "
        + args.toolchange_macro.replace("\\", "\\\\").replace("\n", "\\n")
        + "\\n; SLA name=[sla_video_name] path=[sla_video_path] embedded=[sla_video_embedded]\\n",
        "",
    ]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote setup override: {args.output}")
    print(f"Channels: {channels}")
    print(f"SLA channels: {len(sla_channels)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
